name: colbertv2
params:
  top_k: 3
  chunk_size: 200
  chunk_overlap: 20
  text_source: ocr
  allow_cross_page: true
  max_cross_pages: null
result_name_params: []
checkpoint: /root/autodl-tmp/ylz/models/colbertv2.0
tokenizer_name: bert-base-uncased
max_context_chars: null
