name: m3docrag-iterate-query
params:
  max_iterations: 5
  evaluator_model_name: Qwen3-VL-8B-Instruct
result_name_params:
  - params.max_iterations
  - params.evaluator_model_name
online_colpali:
  backbone_path: /root/autodl-tmp/ylz/models/colpaligemma-3b-mix-448-base
  adapter_path: /root/autodl-tmp/ylz/models/colpali-v1.2
  device: auto
  query_batch_size: 1
