name: m3docrag
params:
  top_k: 1
pdf_embeddings_colpali:
  mmlongbench: /root/autodl-tmp/ylz/NeurIPS_2026/code/benchmarks/mmlongbench/tmp/pdf_embeddings_colpali
  longdocurl: /root/autodl-tmp/ylz/NeurIPS_2026/code/benchmarks/longdocurl/data/pdf_embeddings_colpali/4000-4999
question_embeddings_colpali:
  mmlongbench: /root/autodl-tmp/ylz/NeurIPS_2026/code/benchmarks/mmlongbench/tmp/question_embeddings_colpali
  longdocurl: /root/autodl-tmp/ylz/NeurIPS_2026/code/benchmarks/longdocurl/data/question_embeddings_colpali
