# 注意模型列表按上下文从短到长排序，因为路由器会优先选择列表前面的模型，以避免长上下文模型被短上下文请求占用
model_list:
  - model_name: Qwen/Qwen2.5-VL-7B-Instruct
    litellm_params:
      model: hosted_vllm//data2/jiangjiaqi/ylz/Qwen2.5-VL-7B-Instruct
      api_base: "http://localhost:8001/v1"  # BeiHang GPU 4，throughput 实例
      api_key: "none"
  - model_name: Qwen/Qwen2.5-VL-7B-Instruct
    litellm_params:
      model: hosted_vllm//data2/jiangjiaqi/ylz/Qwen2.5-VL-7B-Instruct
      api_base: "http://localhost:8002/v1"  # BeiHang GPU 5，throughput 实例
      api_key: "none"
  - model_name: Qwen/Qwen2.5-VL-7B-Instruct
    litellm_params:
      model: hosted_vllm//data2/jiangjiaqi/ylz/Qwen2.5-VL-7B-Instruct
      api_base: "http://localhost:8003/v1"  # BeiHang GPU 6，longctx 实例
      api_key: "none"
  - model_name: Qwen/Qwen2.5-VL-7B-Instruct
    litellm_params:
      model: hosted_vllm//data2/jiangjiaqi/ylz/Qwen2.5-VL-7B-Instruct
      api_base: "http://localhost:8004/v1"  # BeiHang GPU 7，longctx 实例
      api_key: "none"
  - model_name: Qwen/Qwen2.5-VL-7B-Instruct
    litellm_params:
      model: hosted_vllm/Qwen/Qwen2.5-VL-7B-Instruct
      api_base: "http://localhost:8000/v1"  # MM GPU 1, 128k 实例
      api_key: "none"      

router_settings:
  routing_strategy: least-busy
  num_retries: 10
