model_list:
- model_name: autodl
  litellm_params:
    model: hosted_vllm/Qwen3-VL-8B-Instruct
    api_base: https://u854510-jyv3-4221f644.westb.seetacloud.com:8443/v1
    api_key: none
  model_info:
    max_tokens: 131072
    input_cost_per_token: 7.5e-08
    output_cost_per_token: 3.0e-07
- model_name: autodl
  litellm_params:
    model: hosted_vllm/Qwen3-VL-8B-Instruct
    api_base: https://uu854510-jyv3-4221f644.westb.seetacloud.com:8443/v1
    api_key: none
  model_info:
    max_tokens: 131072
    input_cost_per_token: 7.5e-08
    output_cost_per_token: 3.0e-07
- model_name: autodl
  litellm_params:
    model: hosted_vllm/Qwen3-VL-8B-Instruct
    api_base: https://u854510-t41j-de061d25.westd.seetacloud.com:8443/v1
    api_key: none
  model_info:
    max_tokens: 131072
    input_cost_per_token: 7.5e-08
    output_cost_per_token: 3.0e-07
- model_name: autodl
  litellm_params:
    model: hosted_vllm/Qwen3-VL-8B-Instruct
    api_base: https://uu854510-t41j-de061d25.westd.seetacloud.com:8443/v1
    api_key: none
  model_info:
    max_tokens: 131072
    input_cost_per_token: 7.5e-08
    output_cost_per_token: 3.0e-07