set -euo pipefail

PROFILE="${1:-64k}"

CUDA_VISIBLE_DEVICES_VALUE="${CUDA_VISIBLE_DEVICES:-1}"
VLLM_BIN="${VLLM_BIN:-/root/autodl-tmp/conda/envs/logma-rag/bin/vllm}"
MODEL_NAME="${MODEL_NAME:-/root/autodl-tmp/ylz/models/Qwen3-VL-8B-Instruct}"
HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-8000}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-}"
ENABLE_CHUNKED_PREFILL="${ENABLE_CHUNKED_PREFILL:-1}"
LIMIT_MM_PER_PROMPT="${LIMIT_MM_PER_PROMPT:-}"
LIMIT_MM_PER_PROMPT_VIDEO="${LIMIT_MM_PER_PROMPT_VIDEO:-0}"
TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE:-1}"
MM_PROCESSOR_CACHE_GB="${MM_PROCESSOR_CACHE_GB:-0}"
ENABLE_PREFIX_CACHING="${ENABLE_PREFIX_CACHING:-1}"
ASYNC_SCHEDULING="${ASYNC_SCHEDULING:-1}"
EXTRA_VLLM_ARGS="${EXTRA_VLLM_ARGS:-}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-1}"
DATA_PARALLEL_SIZE="${DATA_PARALLEL_SIZE:-1}"

COMMON_ARGS=(
  serve
  "${MODEL_NAME}"
  --host "${HOST}"
  --port "${PORT}"
)

case "${PROFILE}" in
  16k)
    DEFAULT_GPU_MEMORY_UTILIZATION="0.5"
    DEFAULT_MAX_MODEL_LEN="16384"
    DEFAULT_MAX_NUM_SEQS="64"
    DEFAULT_MAX_NUM_BATCHED_TOKENS="8192"
    ;;
  32k)
    DEFAULT_GPU_MEMORY_UTILIZATION="0.55"
    DEFAULT_MAX_MODEL_LEN="32768"
    DEFAULT_MAX_NUM_SEQS="64"
    DEFAULT_MAX_NUM_BATCHED_TOKENS="16384"
    ;;
  64k)
    DEFAULT_GPU_MEMORY_UTILIZATION="0.6"
    DEFAULT_MAX_MODEL_LEN="65536"
    DEFAULT_MAX_NUM_SEQS="64"
    DEFAULT_MAX_NUM_BATCHED_TOKENS="32768"
    ;;
  128k)
    DEFAULT_GPU_MEMORY_UTILIZATION="0.65"
    DEFAULT_MAX_MODEL_LEN="131072"
    DEFAULT_MAX_NUM_SEQS="64"
    DEFAULT_MAX_NUM_BATCHED_TOKENS="65536"
    ;;
  256k)
    DEFAULT_GPU_MEMORY_UTILIZATION="0.7"
    DEFAULT_MAX_MODEL_LEN="262144"
    DEFAULT_MAX_NUM_SEQS="64"
    DEFAULT_MAX_NUM_BATCHED_TOKENS="32768"
    ;;
  *)
    echo "Unknown profile: ${PROFILE}" >&2
    echo "Usage: $0 [16k|32k|64k|128k|256k]" >&2
    exit 1
    ;;
esac

GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-${DEFAULT_GPU_MEMORY_UTILIZATION}}"
MAX_MODEL_LEN="${MAX_MODEL_LEN:-${DEFAULT_MAX_MODEL_LEN}}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-${DEFAULT_MAX_NUM_SEQS}}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-${DEFAULT_MAX_NUM_BATCHED_TOKENS}}"

PROFILE_ARGS=(
  --served-model-name Qwen3-VL-8B-Instruct
  --gpu-memory-utilization "${GPU_MEMORY_UTILIZATION}"
  --max-model-len "${MAX_MODEL_LEN}"
  --max-num-seqs "${MAX_NUM_SEQS}"
  --max-num-batched-tokens "${MAX_NUM_BATCHED_TOKENS}"
  --mm-processor-cache-gb "${MM_PROCESSOR_CACHE_GB}"
  --limit-mm-per-prompt.video "${LIMIT_MM_PER_PROMPT_VIDEO}"
  --tensor-parallel-size "${TENSOR_PARALLEL_SIZE}"
  --data-parallel-size "${DATA_PARALLEL_SIZE}"
  --aggregate-engine-logging
)

if [[ "${ENABLE_CHUNKED_PREFILL}" == "1" ]]; then
  PROFILE_ARGS+=(--enable-chunked-prefill)
fi

if [[ "${TRUST_REMOTE_CODE}" == "1" ]]; then
  PROFILE_ARGS+=(--trust-remote-code)
fi

if [[ "${ENABLE_PREFIX_CACHING}" == "1" ]]; then
  PROFILE_ARGS+=(--enable-prefix-caching)
fi

if [[ "${ASYNC_SCHEDULING}" == "1" ]]; then
  PROFILE_ARGS+=(--async-scheduling)
fi

if [[ -n "${LIMIT_MM_PER_PROMPT}" ]]; then
  PROFILE_ARGS+=(--limit-mm-per-prompt "${LIMIT_MM_PER_PROMPT}")
fi

if [[ -n "${EXTRA_VLLM_ARGS}" ]]; then
  # shellcheck disable=SC2206
  EXTRA_ARGS_ARRAY=( ${EXTRA_VLLM_ARGS} )
  PROFILE_ARGS+=("${EXTRA_ARGS_ARRAY[@]}")
fi

echo "Starting vLLM with profile=${PROFILE}, CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES_VALUE}, GPU_MEMORY_UTILIZATION=${GPU_MEMORY_UTILIZATION}, port=${PORT}" >&2
exec env CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES_VALUE}" \
  "${VLLM_BIN}" \
  "${COMMON_ARGS[@]}" \
  "${PROFILE_ARGS[@]}"
